image: quay.io/lifechurch/k8s-deploy-helper:3.0.1
variables:
  # Application deployment domain
  KUBE_DOMAIN: churchonline.us
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

stages:
  - compile
  - test
  - build
  - review
  - staging
  - cypress
  - coverage
  - canary
  - destroy-canary
  - production

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/
    - cache/Cypress

compile:app-review:
  image: node:lts
  stage: compile
  script:
    - yarn install --pure-lockfile
    - yarn build:review
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  except:
    - master
    - integration

compile:app-staging:
  image: node:lts
  stage: compile
  variables:
    GIT_STRATEGY: clone
  script:
    - yarn install --pure-lockfile
    - yarn build:staging
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  only:
    - integration

compile:app-production:
  image: node:lts
  stage: compile
  script:
    - yarn install --pure-lockfile
    - yarn build:production
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  only:
    - master

test:
  stage: test
  image: node:lts
  script:
    - yarn lint
    - yarn flow check
    - yarn coverage # Use coverage to generate coverage report
  artifacts:
    expire_in: 1 day
    paths:
      - coverage/
  except:
    - master

build:image-review:
  stage: build
  cache:
    untracked: false
    policy: pull
  script:
    - command build Dockerfile-app
  dependencies:
    - compile:app-review
  only:
    - branches
  except:
    - master
    - integration

build:image-staging:
  stage: build
  cache:
    untracked: false
    policy: pull
  script:
    - command build Dockerfile-app
    - echo "https://digerati.chopdev.com" > environmentUrl.txt
  artifacts:
    expire_in: 1 hr
    paths:
      - environmentUrl.txt
  dependencies:
    - compile:app-staging
  only:
    - integration

build:image-production:
  stage: build
  cache:
    untracked: false
    policy: pull
  script:
    - command build Dockerfile-app
  dependencies:
    - compile:app-production
  only:
    - master

review:
  stage: review
  cache:
    untracked: false
    policy: pull
  variables:
    CI_ENVIRONMENT_URL: https://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - command deploy
    - echo $CI_ENVIRONMENT_URL > environmentUrl.txt
  artifacts:
    expire_in: 1 hr
    paths:
      - environmentUrl.txt
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
    - integration

cypress:tests-review:
  image: cypress/base:10
  stage: cypress
  allow_failure: true
  script:
    - CI_ENVIRONMENT_URL=`cat environmentUrl.txt`
    - yarn cy:run --record --key $CYPRESS_RECORD_KEY --config baseUrl=$CI_ENVIRONMENT_URL
  artifacts:
    expire_in: 1 day
    paths:
      - cy-coverage/
  dependencies:
    - review
  except:
    - master
    - integration

cypress:tests-staging:
  image: cypress/base:10
  stage: cypress
  allow_failure: true
  script:
    - yarn cy:run --record --key $CYPRESS_RECORD_KEY --config baseUrl="https://digerati.chopdev.com/host_mobile"
  dependencies:
    - build:image-staging
  only:
    - integration

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy app=app-$CI_ENVIRONMENT_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
    - integration

staging:
  stage: staging
  cache:
    untracked: false
    policy: pull
  variables:
    CI_ENVIRONMENT_URL: https://staging.$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: staging
    url: https://staging.$KUBE_DOMAIN
  only:
    - integration

code_coverage_report_master:
  stage: coverage
  allow_failure: true
  cache: {}
  image: node:lts
  variables:
    CC_TEST_REPORTER_ID: 95b2685f3a9425616a05a86a41c0bf0f893c8703a2d19395ac2ea5cdd55a1acd
  script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - yarn install
    - yarn coverage
    - yarn cy:run
    - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.cy.json cy-coverage/lcov.info
    - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.jest.json coverage/lcov.info
    - ./cc-test-reporter  sum-coverage coverage/codeclimate.*.json -p 2
    - ./cc-test-reporter upload-coverage
  only:
    - master

code_coverage_report:
  stage: coverage
  cache: {}
  image: node:lts
  variables:
    CC_TEST_REPORTER_ID: 95b2685f3a9425616a05a86a41c0bf0f893c8703a2d19395ac2ea5cdd55a1acd
  script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.cy.json cy-coverage/lcov.info
    - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.jest.json coverage/lcov.info
    - ./cc-test-reporter  sum-coverage coverage/codeclimate.*.json -p 2
    - ./cc-test-reporter upload-coverage
  except:
    - master

canary:
  stage: canary
  cache: {}
  dependencies: []
  script:
    - command deploy
  environment:
    name: production
    url: https://$KUBE_DOMAIN
  when: manual
  allow_failure: true
  only:
    - master

destroy-canary:
  stage: destroy-canary
  cache: {}
  dependencies: []
  allow_failure: true
  environment:
    name: production
  when: manual
  script:
    - command destroy-canary
  only:
    - master

production:
  stage: production
  cache: {}
  variables:
    CI_ENVIRONMENT_URL: http://$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: production
    url: https://$KUBE_DOMAIN
  when: manual
  allow_failure: false
  only:
    - master
