FROM in.thewardro.be:4567/docker/nginx:1.13.8

COPY config/nginx.sh /etc/service/nginx/run

RUN chmod +x /etc/service/nginx/run

COPY config/nginx/nginx.conf /etc/nginx/

WORKDIR /usr/src/app

COPY dist/* /usr/src/app/

RUN groupadd --gid 1001 cwc && useradd --uid 1001 --gid cwc --shell /bin/bash --create-home cwc && \
	chown -R cwc:cwc /usr/src/app

EXPOSE 80

CMD ["/sbin/my_init"]
