apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: $KUBE_NAMESPACE
  name: app-$CI_ENVIRONMENT_SLUG
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false