---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: app-$CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_SLUG"
    build_id: "$CI_JOB_ID"
    track: stable
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-$CI_ENVIRONMENT_SLUG
      name: app-$CI_ENVIRONMENT_SLUG
      space: $KUBE_NAMESPACE
      track: stable
  template:
    metadata:
      labels:
        name: app-$CI_ENVIRONMENT_SLUG
        app: app-$CI_ENVIRONMENT_SLUG
        space: $KUBE_NAMESPACE
        track: stable
      annotations:
        build_id: "$CI_JOB_ID"
    spec:
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      containers:
      - name: $KUBE_NAMESPACE-app-$CI_ENVIRONMENT_SLUG
        image: $CI_REGISTRY_IMAGE:app-$CI_COMMIT_SHA
        command: ["/sbin/my_init"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /nginx_status
            port: 80
            scheme: HTTP
            httpHeaders:
              - name: Host
                value: 127.0.0.1
              - name: Referer
                value: kubernetes
              - name: User-Agent
                value: kubernetes
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        # env:
        #   {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry
